sudo: required

language: node_js

notifications:
  email: false


# test on two node.js versions: 0.6 and 0.8
node_js:
  - "6"

env:
  - BM_SPACE="ToddsPlace" MANIFEST="manifest.yml" DEPLOY_STATUS_URL="https://api.github.com/repos/$TRAVIS_REPO_SLUG/deployments/$TRAVIS_TAG/statuses"

script:
  - npm test

after_success:
  - bash bin/setup.sh                         #Install cf and aws
  - bash bin/ansibleSetup.sh                  #Install ansible
  - aws s3 cp s3://thetodd/jesse2.tar ./      #Download artifacts
  - chmod 755 jesse2.tar
  - tar -xvzf jesse2.tar

deploy:
    - provider: script
      script: bin/deploy.sh                  #run ansible playbook to deploy app to bluemix
      on:
        branch: staging
