sudo: required

language: node_js

notifications:
  email: false


# test on two node.js versions: 0.6 and 0.8
node_js:
  - "6"

# services:
#   - docker

before_install:
  #Install cloudfoundry
  # Pull container.
  # - sudo apt-get -qq update
  # - 'docker pull webdevops/ansible:alpine-3'
#  - sudo apt-get install ansible
#  - sudo apt-get install python-virtualenv



script:
  - echo hello 

