sudo: required

language: node_js

notifications:
  email: false


node_js:
  - "6"

env:
  - BM_SPACE="Jobgate" MANIFEST="manifest.yml" DEPLOY_STATUS_URL="https://api.github.com/repos/$TRAVIS_REPO_SLUG/deployments/$TRAVIS_TAG/statuses"

script:
  - npm test

after_success:
  - bash bin/setup.sh                         #Install cf and aws
  - bash bin/ansibleSetup.sh                  #Install ansible
  - mkdir tmp
  - aws s3 cp s3://thetodd/jesse2.tar ./tmp     #Download artifacts
  - chmod 755 tmp/jesse2.tar
  - tar -xvzf tmp/jesse2.tar -C ./tmp

deploy:
    - provider: script
      skip_cleanup: true
      script: bin/deploy.sh                  #run ansible playbook to deploy app to bluemix
#      on:
#        branch: staging
