sudo: required

language: node_js

notifications:
  email: false


# test on two node.js versions: 0.6 and 0.8
node_js:
  - "6"

# services:
#   - docker

before_install:
  #Install cloudfoundry
  - bash bin/setup.sh
  - bash bin/ansibleSetup.sh
  - bash apt-get install pip
  - bash aws s3 cp S3_URI ./
  - bash chmod 755 jesse.tar 
  - bash tar -xvzf jesse.tar
 
  # Pull container.
  # - sudo apt-get -qq update
  # - 'docker pull webdevops/ansible:alpine-3'
#  - sudo apt-get install ansible
#  - sudo apt-get install python-virtualenv



script:
  - echo hello 

