# Publish this application to bluemix using ansible
---
- name: Publish the troll-gate to Bluemix using Ansible
  hosts: localhost
  connection: local
  vars:
    username: "{{ lookup('env','BM_USER') }}"
    password: "{{ lookup('env','BM_PASS') }}"
    org: "{{ lookup('env','BM_ORG') }}"
    space: "{{ lookup('env','BM_SPACE') }}"
  tasks:
    - name: CF Login
      shell: "cf login -a https://api.ng.bluemix.net -u {{ username }} -p {{ password  }} -o {{ org }} -s {{ space }}"
      no_log: True
    - name: test
      shell: "cf logs"
