# Publish this application to bluemix using ansible
---
- name: Publish the troll-gate to Bluemix using Ansible
  hosts: localhost
  connection: local
  vars:
    username: "{{ lookup('env','BM_USER') }}"
  tasks:
    - name: CF Login
      shell: "cf login -u {{ username }} -p null"
      no_log: True
    - name: test
      shell: "cf logs"
